### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by craftersmine** [RichysHub/MagicaVoxel-VOX-importer#12]
I downloaded and enabled addon, entry in menu "Import" has appeared, when I tried importing model from .vox file and nothing happened. No model imported. Please help. 

Blender version: 2.80.75. Latest version of addon (2.1)
MagicaVoxel version: 0.99.4.2

Thanks.

**Comment by RichysHub** [comment]
Hey, thanks for letting us know.
I have confirmed that I am using the same Blender, MagicaVoxel, and addon versions as you are. I am seeing the same behaviour.

Currently the addon does not fully support MagicaVoxel's most recent format, which is causing your error. This is in the pipeline.

In MagicaVoxel, try exporting in the vox format. (Don't override your original file, just use this as a go-between file). I believe this exports to the older format version, which should import fine.

![image](https://user-images.githubusercontent.com/20910418/66602112-503dcc00-eba1-11e9-897f-839b6eacb0f4.png)

**Comment by craftersmine** [comment]
> Hey, thanks for letting us know.
> I have confirmed that I am using the same Blender, MagicaVoxel, and addon versions as you are. I am seeing the same behaviour.
> 
> Currently the addon does not fully support MagicaVoxel's most recent format, which is causing your error. This is in the pipeline.
> 
> In MagicaVoxel, try exporting in the vox format. (Don't override your original file, just use this as a go-between file). I believe this exports to the older format version, which should import fine.
> 
> ![image](https://user-images.githubusercontent.com/20910418/66602112-503dcc00-eba1-11e9-897f-839b6eacb0f4.png)

Yep. This works. Thanks for help.

Offtop: I kinda curious, why there is .vox file export when MagicaVoxel saves to .vox file, but they different...

**Comment by wizardgsz** [comment]
Can you share your file @craftersmine? Otherwise, please try [this script (WIP)](https://github.com/wizardgsz/MagicaVoxel-VOX-importer/blob/MATT_MATL/io_scene_vox.py) from MATT_MATL branch.

Anyhow, if you are using Transform/Group/Shape Nodes, they are not supported yet.

Thanks and regards

**Comment by craftersmine** [comment]
> Anyhow, if you are using Transform/Group/Shape Nodes, they are not supported yet.

Well model made by my friend and I don't know, he using them or not (but I think no, because he is newbie in MagicaVoxel).
[VOX_files.zip](https://github.com/RichysHub/MagicaVoxel-VOX-importer/files/3721447/VOX_files.zip)

**Comment by wizardgsz** [comment]
Nice, thanks. 

Later file, saved in latest MagicaVoxel format, contains nTRN/nGRP/LAYR chunks but both files can be loaded using the updated script. MagicaVoxel automatically add them to organize objects, even if you do not use the new "features". For example, you have 8 default layers (from 0 to 8)
Left: old file format i.e. "exported" file, right: saved file in new format.

![Immagine](https://user-images.githubusercontent.com/8364153/66748417-6be9f080-ee87-11e9-94c9-f698a9b7fab6.png)

Thanks again for your feedback
