### ISSUE TITLE
No default palette

### ISSUE THREAD

**Issue by RichysHub** [RichysHub/MagicaVoxel-VOX-importer#5]
Default palette is well defined in the specification of the format, yet currently we do not use this, we simply expect a palette chunk to be present in the .vox file

**Comment by RichysHub** [comment]
Have added support for this. Need to perform a proper test on the code though, ensure palette is used . This probably needs me to write a palette stripper, to get hold of a .vox file with no RGBA chunk

**Comment by RichysHub** [comment]
In testing if the default palette was used, a bug was found causing colors to be different to expectations. This has been fixed in https://github.com/RichysHub/MagicaVoxel-VOX-importer/commit/9e792920fc9c91ec0d07a8226c96ce5a9ea17e52

![vox importer color fix](https://user-images.githubusercontent.com/20910418/31761065-9ed1ce60-b4ae-11e7-87d6-0b236701787f.png)

**Comment by wizardgsz** [comment]
Loading this sample [chr_cat.vox](https://github.com/ephtracy/voxel-model/raw/master/vox/character/chr_cat.vox), I have to correct the `palette.update `in:

```
if not palette:  # no palette provided, use default
        for col in range(256):
            palette.update({col + 1: struct.unpack('<4B', struct.pack('<I', DEFAULT_PALETTE[col]))})
```

Please note the **"<I"** packing DEFAULT_PALETTE (it is ">I" now)

**Comment by RichysHub** [comment]
Okay, I was hesitant to agree, given the above changes, and therefore how confident I was.

However, I have thrown together a [quick script](https://gist.github.com/RichysHub/7869be5d6ccccb45c607e6156d17aab0) (something I clearly never did back in 2017) to visualize the palettes, and I am happy to agree that it is currently incorrect. 

`struct.unpack('<4B', struct.pack('>I', DEFAULT_PALETTE[col]))` produces:

![>I](https://user-images.githubusercontent.com/20910418/65937257-3f5dbf80-e417-11e9-806e-4543c652ab74.png)

`struct.unpack('<4B', struct.pack('<I', DEFAULT_PALETTE[col]))` produces:

![<I](https://user-images.githubusercontent.com/20910418/65937281-57354380-e417-11e9-833e-dae0472d0755.png)

I think there are some slight issues in gamma correction maths currently, and in #8, but I'll detail those there.
