### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by AlexFlorezArt** [RichysHub/MagicaVoxel-VOX-importer#7]
Hello, this looks super useful!  Any chance this will be updated to support the new multi-object world format with material properties conversion?  Honestly I'd be willing to buy that.

**Comment by Swivelgames** [comment]
I'm hoping it's not dead. I just found this and it's very much in line with what I've been looking for.

**Comment by RichysHub** [comment]
Hey guys, apologies for not responding earlier, had not received notification of the issues raised.

I haven't worked on anything related to MagicaVoxel since this project, but after a cursory glance at the new file spec, I see no reason I couldn't update this, once I have time freed up from other projects. 

Be sure to watch the repo, hopefully I'll get things moving in the not too distant future.

**Comment by AlexFlorezArt** [comment]
That’s great! I look forward to it.

**Comment by Gravedrinker** [comment]
Man I've been looking for something like this for ages and now it's not working anymore. :(

That's an amazing job you did on this, I'd be very very VERY interested in this getting updated, I would pay for this addon too.

If this would work in Blender 2.8 with the current magicavoxel it would be a dream but I'd be happy to get it working in Blender 2.79 with the current magicavoxel as well.

I work with magicavoxel a lot and create cyberpunk cityscapes. It's great to get them into Blender but I was always looking for an easy way to get the voxels directly and create physics scenes.

I'd be super happy if you could update this, I hope that's possible.

**Comment by wizardgsz** [comment]
I just "adapted" the script to work in 2.80 syntax. May I upload it?

**Comment by RichysHub** [comment]
@wizardgsz fantastic, I've been slacking on this yet again, I know.
I've been a little caught up on working out how to do it perfectly, to do anything.

Please, do share your adaptation, either as a fork of this repo, or otherwise

**Comment by wizardgsz** [comment]
Np, this is my second script using Python and Blender... never used them before last week 💃 

Here it is my "contrib" in BlenderArtists Community Forums:  [Porting addon to 2.8](https://blenderartists.org/t/porting-addon-to-2-8/1182671)
The archive contains both original 2.74 and 2.80 versions: [io_scene_vox.zip](https://github.com/RichysHub/MagicaVoxel-VOX-importer/files/3664529/io_scene_vox.zip)

[Ported to 2.80 syntax #8 ](https://github.com/RichysHub/MagicaVoxel-VOX-importer/pull/8)

Thanks for your work!
